import builtins
import os
from langchain_core.messages import SystemMessage, AIMessage
from sanitizers.output_validator import output_validator
from logging_config import get_logger

logger = get_logger(__name__)

# HITL configuration via environment variables
# auto-reject: safe default for API/production — never blocks
# auto-approve: for testing — always approves
# console: interactive terminal input — only use in dev
HITL_MODE = os.getenv("HITL_MODE", "auto-reject")
HITL_TIMEOUT = int(os.getenv("HITL_TIMEOUT", "30"))


def ask_human_approval(reason: str) -> bool:
    """
    Human-in-the-Loop approval gate.
    
    Behavior is controlled by the HITL_MODE environment variable:
    - 'auto-reject' (default): Rejects automatically. Safe for API/production.
    - 'auto-approve': Approves automatically. Useful for testing.
    - 'console': Prompts for terminal input. Only for interactive development.
    """
    if HITL_MODE == "auto-approve":
        logger.info(f"[HITL] Auto-approving (HITL_MODE=auto-approve): {reason}")
        return True
    elif HITL_MODE == "console":
        print(f"\n[HUMAN IN THE LOOP REQUIRED]")
        print(f"Reason: {reason}")
        import sys
        if not sys.stdin.isatty():
            logger.warning("[HITL] Non-interactive environment detected, auto-rejecting.")
            return False
        try:
            # Note: For production, replace this with a webhook or async callback pattern
            choice = builtins.input("Approve this action/response? (y/n): ").strip().lower()
            return choice == 'y'
        except (EOFError, KeyboardInterrupt):
            logger.warning("[HITL] No input received, auto-rejecting.")
            return False
        except Exception as e:
            logger.error(f"[HITL] Failed to get human input: {e}")
            return False
    else:  # auto-reject (safe default for API/production)
        logger.warning(f"[HITL] Auto-rejecting (HITL_MODE={HITL_MODE}): {reason}")
        return False

def with_validation_and_recovery(agent_name: str, agent_runnable):
    """
    Phase 8: Output Validation & Recovery Loops
    Wraps an agent's execution to validate its output, retry if unsafe, 
    and escalate to a human if necessary.
    """
    def wrapper(state):
        max_retries = 3
        retries = 0
        
        # We loop to allow regeneration
        while retries <= max_retries:
            logger.info(f"[{agent_name}] Execution attempt {retries + 1}/{max_retries + 1}")
            
            # Execute the agent
            result_state = agent_runnable(state)
            
            # Extract the last message generated by the agent
            if "messages" not in result_state or not result_state["messages"]:
                return result_state
                
            last_message = result_state["messages"][-1]
            if not isinstance(last_message, AIMessage):
                # If it's not an AI message (e.g. human or tool), nothing to validate here
                return result_state
                
            response_text = str(last_message.content)
            
            # 1. Output Validation (Agent B)
            logger.info(f"[{agent_name}] Validating output...")
            validation = output_validator.validate(response_text)
            
            if not validation.is_safe:
                logger.warning(f"[{agent_name}] Validation failed: {validation.reason}")
                
                if retries < max_retries:
                    # 2. Reinjection Loop
                    logger.info(f"[{agent_name}] Reinjecting context for regeneration.")
                    
                    # We append the bad response and a system constraint to the state
                    # so the LLM knows it made a mistake and must fix it.
                    state["messages"].append(last_message)
                    state["messages"].append(SystemMessage(
                        content=f"Validation failed: {validation.reason}. Please regenerate your response and fix this issue."
                    ))
                    retries += 1
                    continue
                else:
                    # Max retries reached, escalate to human
                    logger.error(f"[{agent_name}] Max retries reached for unsafe output.")
                    approved = ask_human_approval(f"Max retries (3) reached for unsafe output: {validation.reason}")
                    if approved:
                        return result_state
                    else:
                        result_state["messages"][-1].content = "[REJECTED] The response was flagged as unsafe and rejected by the user."
                        return result_state
                        
            # Output is safe, check for high-risk
            if validation.needs_human_approval:
                logger.info(f"[{agent_name}] High-risk action detected, requiring human approval.")
                approved = ask_human_approval("High-risk action detected (e.g., booking confirmation).")
                if approved:
                    return result_state
                else:
                    result_state["messages"][-1].content = "[CANCELLED] Action was cancelled by the user."
                    return result_state
                    
            # Safe and no human approval needed
            return result_state
            
        return result_state
        
    return wrapper
