import pandas as pd
import os
from pathlib import Path

def generate_markdown():
    # Paths
    project_root = Path(__file__).resolve().parent.parent
    csv_path = project_root / 'docs' / 'ablation_comparison.csv'
    md_path = project_root / 'docs' / 'ablation_study_results.md'
    
    if not csv_path.exists():
        print(f"Error: {csv_path} does not exist. Run scripts/run_ablation.py first.")
        return

    # Read CSV
    df = pd.read_csv(csv_path)
    
    # Generate Markdown Table
    md_table = df.to_markdown(index=False)
    
    # Write to Markdown file
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write("# Ablation Study Results\n\n")
        f.write("This file is automatically generated from the empirical results of `scripts/run_ablation.py`.\n\n")
        f.write("## Configuration Comparison\n\n")
        f.write("The following table demonstrates the Attack Success Rate (ASR) across different security configurations, validating the defense-in-depth architecture.\n\n")
        f.write(md_table)
        f.write("\n\n")
        
    print(f"Successfully generated markdown tables at {md_path}")

if __name__ == "__main__":
    generate_markdown()
